### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by watilde** [watilde/watilde#3]
Issue test

**Comment by leaysgur** [comment]
test :tea:

**Comment by watilde** [comment]
replay test from email :smile:

On Thu, Mar 5, 2015 at 1:15 PM, Yuji Sugiura notifications@github.com
wrote:

> test [image: :tea:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/watilde/watilde/issues/3#issuecomment-77303787.

## 

Daijiro Wachi

**Comment by watilde** [comment]
Seems ok. Thanks for helps me! @leader22
